### ISSUE TITLE
Node Free Memory calculation

### ISSUE THREAD

**Issue by alex6058** [Redislabs-Solution-Architects/RedisEnterprisePrometheus#1]
Hello Chris,

I suggest the update of the formula for Node Free Memory calculation:
```
alert: Node Free Memory
     expr: round((100 * node_free_memory/node_available_memory)) <= 15
     for: 2m
```

In my environment, `node_free_memory` is always greater than `node_available_memory` and this makes sense, as the `node_free_memory` shows the system memory, but this means the original fraction always will calculate value greater than 1 and whole formula result will be 100+ and therefore never can be <15. Should we flip the fraction?

I suggest the update of the formula for Node Free Memory calculation:

```
alert: Node Free Memory
     expr: round((100 * node_available_memory/node_free_memory)) <= 15
     for: 2m
```

Thank you

**Comment by maguec** [comment]
Thanks for the suggestion
